### ISSUE TITLE
<cmath>  instead of <math.h>

### ISSUE THREAD

**Issue by carlosjoserg** [andreucm/cpp_course#1]
In C++, the <cmath> library is used for what it used to be in <math.h> [here](https://github.com/andreucm/cpp_course/blob/master/07_std_math/std_math.cpp#L3)

So, one invokes the functions using the `std::` namespace:

```c++
std::cout << "cos(0): " << std::cos(0.0) << std::endl;

std::cout << "fabs(-1.345) = " << std::abs(-1.345) << std::endl; // or std::fabs

```

**Comment by andreucm** [comment]
Thanks! 
Fixed at https://github.com/andreucm/cpp_course/commit/14fbcc825da8995edd84fd50a0f9bb7602a9c9d9
